Am 38
garusis/marint_web pull request #65
Opened 2017-03-04 03:36 UTC by alphonse92

Issue #38: resolved.

2017-03-05 01:12 UTC, garusis requested changes
Please, remove hard coded items and check the relation's implementation that exists. I'm fixing them right now, but take them in mind.

2017-03-05 01:12 UTC, garusis commented on development/modules/users/templates/activity.html
>              <h6>Marco Lino Alvarez Burgos</h6>
Why is this hard coded? You should get the instructor.

2017-03-05 01:12 UTC, garusis commented on development/modules/users/templates/activity.html
> +              <h6 ng-show="$paginator_item.publication.active">Marco Lino Alvarez Burgos | Publicado: 13 Feb 2017 Comentarios: 2</h6>
Hard coded again.

2017-03-05 01:12 UTC, garusis commented on development/modules/students/servicesStudents.js
> +    CourseStudentRelation.prototype.getAll = function () {
Please, follow the standard in others relation builders. This method should be get and give you the option to use a custom filter. https://github.com/garusis/marint_web/blob/4496c9c47f7912f99ea9b12dcb20ca77258ea081/development/modules/students/servicesStudents.js#L86

2017-03-05 02:41 UTC, garusis commented on development/modules/students/servicesStudents.js
> +                  .error(function (error) {
Error is not an ES Promises standard method. Please use then and catch at Promises.

2017-03-05 02:41 UTC, garusis commented on development/modules/students/servicesStudents.js
> +            comment.getPublication = function () {
Why you're not using NewsService if that have all you need to that the same? Please, do not reinvent the wheel, be modular.

2017-03-06 14:24 UTC, alphonse92 commented on development/modules/users/templates/activity.html
>              <h6>Marco Lino Alvarez Burgos</h6>
I forget that

2017-03-06 14:38 UTC, alphonse92 commented on development/modules/students/servicesStudents.js
> +    CourseStudentRelation.prototype.getAll = function () {
resolved.

2017-03-06 17:47 UTC, garusis approved these changes

2017-03-06 17:47 UTC, merged